import React, { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock, Copy, Download, ExternalLink, FileText, Loader2, PackageCheck, RefreshCw, Send, ShieldCheck, ShoppingCart, Truck, X } from "lucide-react";
import { api } from "./api";

const caixa = "rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800";
const input = "mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none dark:border-slate-600 dark:bg-slate-900";
const money = valor => Number(valor || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const date = valor => valor ? new Date(valor).toLocaleString("pt-BR") : "—";
const labels = { link_nao_enviado: "Link nao enviado", enviado: "Enviado", link_acessado: "Link acessado", formulario_iniciado: "Formulario iniciado", rascunho_salvo: "Rascunho salvo", respondido: "Respondido", resposta_alterada: "Resposta alterada", vencido: "Vencido", recusado: "Recusou", cancelado: "Cancelado", aguardando: "Aguardando", respondida: "Com respostas", finalizada: "Finalizada", encerrada: "Encerrada", gerado: "Gerado", confirmado: "Conferido", recebido_parcialmente: "Recebido parcialmente", recebido: "Recebido", divergente: "Divergente", pendente: "Pendente" };
function Tag({ status }) { const bom = ["respondido","resposta_alterada","finalizada","recebido"].includes(status), ruim = ["vencido","cancelado","divergente","recusado"].includes(status); return <span className={`inline-flex rounded-full px-2 py-1 text-[11px] font-semibold ${bom?"bg-emerald-100 text-emerald-700":ruim?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{labels[status] || status?.replaceAll("_"," ")}</span>; }
function Aviso({ aviso, fechar }) { if(!aviso)return null; return <div className={`flex items-center justify-between rounded-xl border px-4 py-3 text-sm ${aviso.tipo==="erro"?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}><span>{aviso.texto}</span><button onClick={fechar}><X size={16}/></button></div>; }

function EstoqueMinimo({ itens }) {
  return <div className={caixa+" overflow-hidden"}><div className="flex flex-col gap-2 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between dark:border-slate-700"><div><h3 className="flex items-center gap-2 font-semibold"><AlertTriangle size={16} className="text-amber-500"/>Itens abaixo do estoque m&iacute;nimo</h3><p className="mt-1 text-xs text-slate-500">Comprar somente a diferen&ccedil;a necess&aacute;ria para atingir o m&iacute;nimo.</p></div><span className="w-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-700">{itens.length} para repor</span></div>
    {itens.length===0?<div className="p-6 text-center text-sm text-slate-400">Nenhum item abaixo do m&iacute;nimo definido no Estoque.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b border-slate-100 text-left text-xs uppercase text-slate-400 dark:border-slate-700"><th className="p-3">Item</th><th className="p-3">Categoria</th><th className="p-3 text-right">Atual</th><th className="p-3 text-right">M&iacute;nimo</th><th className="p-3 text-right">Comprar</th></tr></thead><tbody>{itens.map(item=><tr key={item.codigo} className="border-b border-slate-50 hover:bg-slate-50/60 dark:border-slate-700/50 dark:hover:bg-slate-700/20"><td className="p-3 font-medium">{item.nome}<div className="font-mono text-[11px] text-slate-400">{item.codigo}</div></td><td className="p-3 text-slate-500">{item.categoria||"?"}</td><td className="p-3 text-right">{item.estoqueAtual} {item.unidade}</td><td className="p-3 text-right font-medium">{item.estoqueMinimo} {item.unidade}</td><td className="p-3 text-right font-semibold text-[#7A1420]">{item.quantidadeSugerida} {item.unidade}</td></tr>)}</tbody></table></div>}
  </div>;
}

function NovaCotacao({ painel, fechar, concluir }) {
  const [selecionados,setSelecionados]=useState({}); const [quantidades,setQuantidades]=useState({}); const [fornecedores,setFornecedores]=useState({});
  const [prazo,setPrazo]=useState(()=>{const d=new Date(Date.now()+3*86400000);return d.toISOString().slice(0,16)}); const [observacoes,setObservacoes]=useState(""); const [salvando,setSalvando]=useState(false); const [erro,setErro]=useState("");
  useEffect(()=>setQuantidades(Object.fromEntries((painel.sugestoes||[]).map(i=>[i.codigo,i.quantidadeSugerida||1]))),[painel]);
  async function criar(){const itens=painel.sugestoes.filter(i=>selecionados[i.codigo]).map(i=>({insumoCodigo:i.codigo,quantidade:Number(quantidades[i.codigo]||0)}));const fornecedorIds=painel.fornecedores.filter(f=>fornecedores[f.id]).map(f=>f.id);if(!fornecedorIds.length||!itens.length){setErro("Selecione primeiro os fornecedores e depois os produtos.");return}setSalvando(true);setErro("");try{const cotacao=await api.criarCotacaoInteligente({itens,fornecedorIds,prazoResposta:new Date(prazo).toISOString(),observacoes});try{const envio=await api.enviarCotacaoWhatsapp(cotacao.codigo);concluir({...cotacao,envios:envio.resultados||[],modoEnvio:envio.modo});}catch(envioErro){concluir({...cotacao,envios:[],erroEnvio:envioErro?.message||"Falha no envio pelo WhatsApp."});}}catch(e){setErro(e?.message||"Nao foi possivel criar.")}finally{setSalvando(false)}}
  return <div className={caixa+" p-5 space-y-5"}><div className="flex items-start justify-between"><div><h3 className="font-semibold">Nova cota&ccedil;&atilde;o</h3><p className="text-xs text-slate-500">Primeiro selecione os fornecedores cadastrados; depois escolha os produtos abaixo do m&iacute;nimo.</p></div><button onClick={fechar}><X size={18}/></button></div>{erro&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</p>}
    <div><h4 className="mb-2 text-sm font-semibold">1. Fornecedores cadastrados no sistema</h4><div className="flex flex-wrap gap-2">{painel.fornecedores.map(f=><label key={f.id} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" checked={!!fornecedores[f.id]} onChange={e=>setFornecedores({...fornecedores,[f.id]:e.target.checked})} className="accent-[#7A1420]"/><span>{f.nome}</span><span className="text-xs text-slate-400">{f.telefone||"sem WhatsApp"}</span></label>)}</div></div>
    <div><h4 className="mb-2 text-sm font-semibold">2. Produtos e quantidades</h4><div className="grid gap-2 lg:grid-cols-2">{painel.sugestoes.map(item=><label key={item.codigo} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" checked={!!selecionados[item.codigo]} onChange={e=>setSelecionados({...selecionados,[item.codigo]:e.target.checked})} className="accent-[#7A1420]"/><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{item.nome}</div><div className="text-xs text-slate-400">{item.estoqueAtual} / m&iacute;nimo {item.estoqueMinimo} {item.unidade}</div></div><input disabled={!selecionados[item.codigo]} type="number" min="0.001" step="0.001" value={quantidades[item.codigo]??""} onChange={e=>setQuantidades({...quantidades,[item.codigo]:e.target.value})} className="w-24 rounded-lg border border-slate-200 px-2 py-1.5 text-right text-sm"/></label>)}</div>{!painel.sugestoes.length&&<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">Nenhum produto est&aacute; abaixo do estoque m&iacute;nimo.</p>}</div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">Prazo m&aacute;ximo para resposta<input type="datetime-local" value={prazo} onChange={e=>setPrazo(e.target.value)} className={input}/></label><label className="text-xs text-slate-500">Observa&ccedil;&otilde;es<input value={observacoes} onChange={e=>setObservacoes(e.target.value)} className={input}/></label></div><div className="flex justify-end"><button disabled={salvando||!painel.sugestoes.length} onClick={criar} className="rounded-xl bg-[#7A1420] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{salvando?"Criando e enviando...":"Criar e enviar pelo WhatsApp"}</button></div></div>;
}

function Comparativo({ cotacao, fechar, finalizado }) {
  const [selecoes,setSelecoes]=useState(()=>Object.fromEntries(cotacao.itens.map(item=>{const op=[...(item.propostas||[])].filter(p=>p.precoUnitario!=null&&p.disponivel).sort((a,b)=>a.precoUnitario-b.precoUnitario)[0];return [item.id,op?.id||""]}))); const [justificativa,setJustificativa]=useState(""); const [salvando,setSalvando]=useState(false); const [erro,setErro]=useState("");
  async function concluir(){if(Object.values(selecoes).some(v=>!v)){setErro("Escolha uma proposta para cada item.");return}setSalvando(true);try{const r=await api.finalizarCotacao(cotacao.codigo,{selecoes:cotacao.itens.map(i=>({cotacaoItemId:i.id,propostaItemId:selecoes[i.id]})),justificativa});finalizado(r);}catch(e){setErro(e?.message||"Nao foi possivel finalizar.")}finally{setSalvando(false)}}
  return <div className={caixa+" p-5 space-y-4"}><div className="flex justify-between"><div><h3 className="font-semibold">Comparativo {cotacao.codigo}</h3><p className="text-xs text-slate-500">Escolha fornecedores diferentes por produto, se desejar.</p></div><button onClick={fechar}><X size={18}/></button></div>{erro&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</p>}
    <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-400"><th className="p-3">Produto</th><th className="p-3">Fornecedor</th><th className="p-3 text-right">Pre&ccedil;o</th><th className="p-3">Marca</th><th className="p-3">Prazo</th><th className="p-3">Escolha</th></tr></thead><tbody>{cotacao.itens.flatMap(item=>(item.propostas||[]).filter(p=>p.precoUnitario!=null).sort((a,b)=>a.precoUnitario-b.precoUnitario).map((p,i)=><tr key={p.id} className="border-b border-slate-100"><td className="p-3 font-medium">{item.nome}<div className="text-xs text-slate-400">{item.quantidade} {item.unidade}</div></td><td className="p-3">{p.fornecedor}</td><td className="p-3 text-right font-semibold">{money(p.precoUnitario)}{i===0&&<span className="ml-2 text-[10px] text-emerald-600">MENOR</span>}</td><td className="p-3">{p.marca||"—"}</td><td className="p-3">{p.prazoDias==null?"—":p.prazoDias+" dias"}</td><td className="p-3"><input type="radio" name={item.id} checked={selecoes[item.id]===p.id} onChange={()=>setSelecoes({...selecoes,[item.id]:p.id})} className="accent-[#7A1420]"/></td></tr>))}</tbody></table></div>
    <label className="block text-xs text-slate-500">Justificativa quando n&atilde;o escolher o menor pre&ccedil;o<textarea value={justificativa} onChange={e=>setJustificativa(e.target.value)} className={input+" min-h-16"}/></label><div className="flex justify-end"><button disabled={salvando} onClick={concluir} className="rounded-xl bg-[#7A1420] px-5 py-2.5 text-sm font-semibold text-white">{salvando?"Gerando pedidos...":"Finalizar e gerar pedidos"}</button></div></div>;
}

function ReceberPedido({ pedido, fechar, concluir }) {
  const [nota,setNota]=useState({numeroNotaFiscal:"",serieNotaFiscal:"",chaveAcesso:"",dataEmissao:"",dataEntrada:new Date().toISOString().slice(0,10),frete:pedido.frete||0,desconto:pedido.desconto||0,impostos:0,valorTotal:pedido.valorTotal,observacoes:""});
  const [itens,setItens]=useState(pedido.itens.map(i=>({pedidoCompraItemId:i.id,quantidadeRecebida:i.quantidade,quantidadeRecusada:0,fatorConversaoEstoque:1,unidade:i.unidade,valorUnitarioRecebido:i.custoUnitario,marcaRecebida:i.marca||"",situacao:"RECEBIDO_CORRETAMENTE",lote:"",dataValidade:"",observacoes:""}))); const [salvando,setSalvando]=useState(false); const [erro,setErro]=useState("");
  function mudar(i,c,v){setItens(x=>x.map((a,n)=>n===i?{...a,[c]:v}:a))}
  async function salvar(){setSalvando(true);setErro("");try{const r=await api.criarRecebimentoCompra(pedido.id,{...nota,dataEmissao:nota.dataEmissao||undefined,dataEntrada:nota.dataEntrada||undefined,frete:Number(nota.frete||0),desconto:Number(nota.desconto||0),impostos:Number(nota.impostos||0),valorTotal:Number(nota.valorTotal||0),itens:itens.map(i=>({...i,quantidadeRecebida:Number(i.quantidadeRecebida||0),quantidadeRecusada:Number(i.quantidadeRecusada||0),fatorConversaoEstoque:Number(i.fatorConversaoEstoque||1),valorUnitarioRecebido:Number(i.valorUnitarioRecebido||0),dataValidade:i.dataValidade||undefined}))});concluir(r)}catch(e){setErro(e?.message||"Nao foi possivel registrar o recebimento.")}finally{setSalvando(false)}}
  return <div className={caixa+" p-5 space-y-4"}><div className="flex justify-between"><div><h3 className="font-semibold">Receber mercadoria &middot; {pedido.codigo}</h3><p className="text-xs text-slate-500">Confira a mercadoria e a nota. O saldo ainda n&atilde;o ser&aacute; alterado.</p></div><button onClick={fechar}><X size={18}/></button></div>{erro&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{erro}</p>}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-slate-500">N&uacute;mero da NF<input value={nota.numeroNotaFiscal} onChange={e=>setNota({...nota,numeroNotaFiscal:e.target.value})} className={input}/></label><label className="text-xs text-slate-500">S&eacute;rie<input value={nota.serieNotaFiscal} onChange={e=>setNota({...nota,serieNotaFiscal:e.target.value})} className={input}/></label><label className="text-xs text-slate-500 lg:col-span-2">Chave de acesso<input value={nota.chaveAcesso} onChange={e=>setNota({...nota,chaveAcesso:e.target.value})} className={input}/></label><label className="text-xs text-slate-500">Data emiss&atilde;o<input type="date" value={nota.dataEmissao} onChange={e=>setNota({...nota,dataEmissao:e.target.value})} className={input}/></label><label className="text-xs text-slate-500">Data entrada<input type="date" value={nota.dataEntrada} onChange={e=>setNota({...nota,dataEntrada:e.target.value})} className={input}/></label><label className="text-xs text-slate-500">Frete<input type="number" value={nota.frete} onChange={e=>setNota({...nota,frete:e.target.value})} className={input}/></label><label className="text-xs text-slate-500">Valor total<input type="number" value={nota.valorTotal} onChange={e=>setNota({...nota,valorTotal:e.target.value})} className={input}/></label></div>
  <div className="space-y-3">{pedido.itens.map((p,i)=><div key={p.id} className="rounded-xl border border-slate-200 p-4"><div className="font-medium">{p.nome} <span className="text-xs text-slate-400">pedido: {p.quantidade} {p.unidade}</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-xs text-slate-500">Recebida<input type="number" min="0" step="0.001" value={itens[i].quantidadeRecebida} onChange={e=>mudar(i,"quantidadeRecebida",e.target.value)} className={input}/></label><label className="text-xs text-slate-500">Recusada<input type="number" min="0" step="0.001" value={itens[i].quantidadeRecusada} onChange={e=>mudar(i,"quantidadeRecusada",e.target.value)} className={input}/></label><label className="text-xs text-slate-500">Convers&atilde;o p/ estoque<input type="number" min="0.0001" step="0.0001" value={itens[i].fatorConversaoEstoque} onChange={e=>mudar(i,"fatorConversaoEstoque",e.target.value)} className={input}/></label><label className="text-xs text-slate-500">Valor unit&aacute;rio<input type="number" min="0" step="0.0001" value={itens[i].valorUnitarioRecebido} onChange={e=>mudar(i,"valorUnitarioRecebido",e.target.value)} className={input}/></label><label className="text-xs text-slate-500">Situa&ccedil;&atilde;o<select value={itens[i].situacao} onChange={e=>mudar(i,"situacao",e.target.value)} className={input}><option value="RECEBIDO_CORRETAMENTE">Recebido corretamente</option><option value="RECEBIDO_PARCIALMENTE">Recebido parcialmente</option><option value="PRODUTO_DIVERGENTE">Produto divergente</option><option value="QUANTIDADE_DIVERGENTE">Quantidade divergente</option><option value="VALOR_DIVERGENTE">Valor divergente</option><option value="PRODUTO_RECUSADO">Produto recusado</option><option value="PRODUTO_AVARIADO">Produto avariado</option></select></label><label className="text-xs text-slate-500">Lote<input value={itens[i].lote} onChange={e=>mudar(i,"lote",e.target.value)} className={input}/></label><label className="text-xs text-slate-500">Validade<input type="date" value={itens[i].dataValidade} onChange={e=>mudar(i,"dataValidade",e.target.value)} className={input}/></label></div></div>)}</div><div className="flex justify-end"><button disabled={salvando} onClick={salvar} className="rounded-xl bg-[#7A1420] px-5 py-2.5 text-sm font-semibold text-white">{salvando?"Registrando...":"Registrar conferencia"}</button></div></div>;
}

export default function ComprasCotacoes({ aba, apiStatus }) {
  const [painel,setPainel]=useState({sugestoes:[],cotacoes:[],fornecedores:[],pedidos:[],indicadores:{}}); const [recebimentos,setRecebimentos]=useState([]); const [historico,setHistorico]=useState([]); const [carregando,setCarregando]=useState(true); const [falhaCarregamento,setFalhaCarregamento]=useState(""); const [aviso,setAviso]=useState(null); const [nova,setNova]=useState(false); const [comparar,setComparar]=useState(null); const [receber,setReceber]=useState(null); const [envios,setEnvios]=useState([]);
  async function carregar(){setCarregando(true);setFalhaCarregamento("");try{const [p,r,h]=await Promise.all([api.getPainelCotacoes(),api.getRecebimentosCompra(),api.getHistoricoPrecosCompra()]);setPainel(p);setRecebimentos(r.data||[]);setHistorico(h.data||[]);}catch(e){const mensagem=e?.message||"Nao foi possivel carregar Compras.";setFalhaCarregamento(mensagem);setAviso({tipo:"erro",texto:mensagem})}finally{setCarregando(false)}}
  useEffect(()=>{if(apiStatus==="online")carregar();},[apiStatus]);
  async function enviar(cotacao){try{const r=await api.enviarCotacaoWhatsapp(cotacao.codigo);setEnvios(r.resultados||[]);setAviso({tipo:"ok",texto:r.modo==="links_whatsapp"?"Links prontos. Abra o WhatsApp de cada fornecedor para enviar.":"Cotacao processada pelo WhatsApp."});await carregar();}catch(e){setAviso({tipo:"erro",texto:e?.message||"Falha no envio."})}}
  async function novoLink(cotacao,participacao){try{const r=await api.gerarNovoLinkCotacao(cotacao.codigo,participacao.id);await navigator.clipboard?.writeText(r.linkFormulario);setAviso({tipo:"ok",texto:"Novo link gerado e copiado para "+participacao.fornecedor+"."});await carregar();}catch(e){setAviso({tipo:"erro",texto:e?.message||"Falha ao gerar novo link."})}}
  async function pdf(pedido){try{const blob=await api.baixarPdfPedido(pedido.id);const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener");setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setAviso({tipo:"erro",texto:e?.message})}}
  async function confirmar(r){if(!window.confirm("Confirmar a entrada no estoque? Esta acao atualizara saldos e custos."))return;try{const x=await api.confirmarEntradaRecebimento(r.id);setAviso({tipo:"ok",texto:x.mensagem});await carregar();}catch(e){setAviso({tipo:"erro",texto:e?.message})}}
  if(apiStatus!=="online")return <div className={caixa+" p-8 text-center text-sm text-amber-700"}><AlertTriangle className="mx-auto mb-2"/>Conecte a API para usar cota&ccedil;&otilde;es persistentes e links seguros.</div>;
  if(carregando)return <div className="flex items-center justify-center p-12 text-slate-500"><Loader2 className="mr-2 animate-spin"/>Carregando compras...</div>;
  if(falhaCarregamento)return <div className={caixa+" border-red-200 p-8 text-center text-sm text-red-700"}><AlertTriangle className="mx-auto mb-3"/><p className="font-semibold">N&atilde;o foi poss&iacute;vel consultar o estoque m&iacute;nimo.</p><p className="mt-1 text-xs">{falhaCarregamento}</p><button onClick={carregar} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#7A1420] px-4 py-2.5 font-semibold text-white"><RefreshCw size={15}/>Tentar novamente</button></div>;
  const i=painel.indicadores||{};
  return <div className="space-y-4"><Aviso aviso={aviso} fechar={()=>setAviso(null)}/>
    {aba==="cotacoes"&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Abaixo do minimo",i.abaixoMinimo,AlertTriangle],["Aguardando respostas",i.aguardandoResposta,Clock],["Finalizadas",i.finalizadas,CheckCircle2],["Economia acumulada",money(i.economiaAcumulada),ShoppingCart]].map(([l,v,Ic])=><div key={l} className={caixa+" p-4"}><Ic size={17} className="text-[#7A1420]"/><div className="mt-2 text-2xl font-semibold">{v||0}</div><div className="text-xs text-slate-500">{l}</div></div>)}</div><EstoqueMinimo itens={painel.sugestoes}/><div className="flex justify-end"><button onClick={()=>setNova(!nova)} className="rounded-xl bg-[#7A1420] px-4 py-2.5 text-sm font-semibold text-white">Nova cota&ccedil;&atilde;o</button></div>{nova&&<NovaCotacao painel={painel} fechar={()=>setNova(false)} concluir={async c=>{setNova(false);setEnvios(c.envios||[]);setAviso({tipo:c.erroEnvio?"erro":"ok",texto:c.erroEnvio?c.codigo+" criada, mas o WhatsApp falhou: "+c.erroEnvio:c.modoEnvio==="links_whatsapp"?c.codigo+" criada. Abra os botoes abaixo para enviar no WhatsApp.":c.codigo+" criada e enviada pela API do WhatsApp."});await carregar();}}/>}{comparar&&<Comparativo cotacao={comparar} fechar={()=>setComparar(null)} finalizado={async r=>{setComparar(null);setAviso({tipo:"ok",texto:r.pedidos.length+" pedido(s) gerado(s) em PDF."});await carregar();}}/>}
      {envios.length>0&&<div className={caixa+" p-4"}><div className="flex justify-between"><h3 className="font-semibold">Envio pelo WhatsApp</h3><button onClick={()=>setEnvios([])}><X size={17}/></button></div><div className="mt-3 flex flex-wrap gap-2">{envios.map(e=><a key={e.participacaoId} href={e.urlWhatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 text-sm font-medium text-white"><Send size={14}/>{e.fornecedor}</a>)}</div></div>}
      <div className="space-y-3">{painel.cotacoes.map(c=><div key={c.id} className={caixa+" p-4"}><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-slate-400">{c.codigo}</span><Tag status={c.status}/><span className="text-xs text-slate-400">prazo {date(c.prazoResposta)}</span></div><div className="mt-2 font-semibold">{c.itens.length} produto(s) &middot; {c.propostas.length} fornecedor(es)</div><div className="mt-2 flex flex-wrap gap-2">{c.propostas.map(p=><span key={p.id} className="inline-flex items-center gap-1 rounded-lg bg-slate-50 px-2 py-1 text-xs dark:bg-slate-700"><Tag status={p.status}/> {p.fornecedor}{p.total!=null?" · "+money(p.total):""}{p.respondeu&&c.status!=="finalizada"&&<button onClick={()=>novoLink(c,p)} title="Liberar nova edicao" className="ml-1 rounded p-1 text-[#7A1420] hover:bg-red-50"><Copy size={11}/></button>}</span>)}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>enviar(c)} disabled={["finalizada","encerrada","cancelada"].includes(c.status)} className="inline-flex items-center gap-1 rounded-xl border border-emerald-300 px-3 py-2 text-xs font-semibold text-emerald-700 disabled:opacity-40"><Send size={13}/>WhatsApp</button><button onClick={()=>setComparar(c)} disabled={!c.itens.some(x=>x.propostas?.some(p=>p.precoUnitario!=null))||c.status==="finalizada"} className="rounded-xl border border-[#7A1420] px-3 py-2 text-xs font-semibold text-[#7A1420] disabled:opacity-40">Comparar e escolher</button></div></div>{c.melhor&&<div className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">Melhor custo total atual: <strong>{c.melhor.fornecedor} &middot; {money(c.melhor.total)}</strong> &middot; economia estimada {money(c.economiaTotal)}</div>}</div>)}</div></>}
    {aba==="pedidos"&&<><div className="grid gap-3 sm:grid-cols-3"><div className={caixa+" p-4"}><Truck/><strong className="mt-2 block text-2xl">{painel.pedidos.length}</strong><span className="text-xs text-slate-500">Pedidos armazenados</span></div><div className={caixa+" p-4"}><Clock/><strong className="mt-2 block text-2xl">{i.pedidosAguardando||0}</strong><span className="text-xs text-slate-500">Aguardando entrega</span></div><div className={caixa+" p-4"}><FileText/><strong className="mt-2 block text-2xl">PDF</strong><span className="text-xs text-slate-500">Documento em cada pedido</span></div></div><div className={caixa+" overflow-x-auto"}><table className="w-full min-w-[820px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-400"><th className="p-3">Pedido</th><th className="p-3">Fornecedor</th><th className="p-3">Cota&ccedil;&atilde;o</th><th className="p-3">Itens</th><th className="p-3 text-right">Total</th><th className="p-3">Status</th><th className="p-3"></th></tr></thead><tbody>{painel.pedidos.map(p=><tr key={p.id} className="border-b border-slate-100"><td className="p-3 font-mono text-xs">{p.codigo}</td><td className="p-3 font-medium">{p.fornecedor}</td><td className="p-3">{p.cotacaoCodigo||"—"}</td><td className="p-3">{p.itens.length}</td><td className="p-3 text-right">{money(p.valorTotal)}</td><td className="p-3"><Tag status={p.status}/></td><td className="p-3"><div className="flex justify-end gap-1"><button onClick={()=>pdf(p)} title="PDF" className="rounded-lg p-2 hover:bg-slate-100"><Download size={15}/></button>{!["recebido","cancelado"].includes(p.status)&&<button onClick={()=>setReceber(p)} className="rounded-lg bg-[#7A1420] px-3 py-2 text-xs font-semibold text-white">Receber</button>}</div></td></tr>)}</tbody></table></div>{receber&&<ReceberPedido pedido={receber} fechar={()=>setReceber(null)} concluir={async r=>{setReceber(null);setAviso({tipo:r.divergencias?.length?"erro":"ok",texto:r.divergencias?.length?r.divergencias.join("; "):"Conferencia registrada. Confirme a entrada na aba Recebimentos."});await carregar();}}/>}</>}
    {aba==="recebimentos"&&<div className="space-y-3">{recebimentos.map(r=><div key={r.id} className={caixa+" p-4"}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><strong>{r.pedidoCodigo}</strong><Tag status={r.status}/>{r.estoqueConfirmadoEm&&<span className="text-xs text-emerald-600">Estoque confirmado {date(r.estoqueConfirmadoEm)}</span>}</div><div className="mt-1 text-sm text-slate-500">{r.fornecedor} &middot; NF {r.numeroNotaFiscal||"nao informada"} &middot; {r.itens.length} item(ns)</div>{r.divergencias?.length>0&&<div className="mt-2 rounded-lg bg-amber-50 p-2 text-xs text-amber-800">{r.divergencias.join("; ")}</div>}</div>{!r.estoqueConfirmadoEm&&<button onClick={()=>confirmar(r)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"><PackageCheck size={16}/>Confirmar entrada no estoque</button>}</div></div>)}{!recebimentos.length&&<div className={caixa+" p-8 text-center text-sm text-slate-400"}>Nenhum recebimento registrado.</div>}</div>}
    {aba==="historico"&&<div className={caixa+" overflow-x-auto"}><div className="border-b p-4"><h3 className="font-semibold">Hist&oacute;rico de pre&ccedil;os e compras</h3><p className="text-xs text-slate-500">Gerado somente ap&oacute;s a entrada confirmada no estoque.</p></div><table className="w-full min-w-[780px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-400"><th className="p-3">Data</th><th className="p-3">Produto</th><th className="p-3">Fornecedor</th><th className="p-3 text-right">Quantidade</th><th className="p-3 text-right">Custo final</th><th className="p-3">Pedido / NF</th></tr></thead><tbody>{historico.map(h=><tr key={h.id} className="border-b border-slate-100"><td className="p-3">{date(h.criadoEm)}</td><td className="p-3 font-medium">{h.produto}<div className="font-mono text-xs text-slate-400">{h.codigo}</div></td><td className="p-3">{h.fornecedor}</td><td className="p-3 text-right">{h.quantidade} {h.unidade}</td><td className="p-3 text-right">{money(h.custoFinal)}</td><td className="p-3">{h.pedido||"—"} / {h.notaFiscal||"—"}</td></tr>)}</tbody></table></div>}
    {aba==="configuracoes"&&<div className="grid gap-4 lg:grid-cols-2"><div className={caixa+" p-5"}><ShieldCheck className="text-emerald-600"/><h3 className="mt-3 font-semibold">Links seguros por fornecedor</h3><p className="mt-2 text-sm text-slate-500">Tokens aleat&oacute;rios, prazo de validade, bloqueio ap&oacute;s envio, registro de acesso e isolamento entre fornecedores.</p></div><div className={caixa+" p-5"}><Send className="text-[#7A1420]"/><h3 className="mt-3 font-semibold">WhatsApp</h3><p className="mt-2 text-sm text-slate-500">Com credenciais Meta configuradas, o template &eacute; enviado pela API. Sem credenciais, o ERP abre a mensagem pronta no WhatsApp com o mesmo link seguro.</p></div><div className={caixa+" p-5 lg:col-span-2"}><h3 className="font-semibold">Fluxo protegido</h3><div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-600"><span className="rounded-lg bg-slate-100 px-3 py-2">Estoque m&iacute;nimo</span><span>&rarr;</span><span className="rounded-lg bg-slate-100 px-3 py-2">Formul&aacute;rio</span><span>&rarr;</span><span className="rounded-lg bg-slate-100 px-3 py-2">Comparativo</span><span>&rarr;</span><span className="rounded-lg bg-slate-100 px-3 py-2">Pedido PDF</span><span>&rarr;</span><span className="rounded-lg bg-slate-100 px-3 py-2">Confer&ecirc;ncia</span><span>&rarr;</span><span className="rounded-lg bg-slate-100 px-3 py-2">Entrada no estoque</span></div></div></div>}
  </div>;
}
